import React, { useState } from "react";
import PrintView from "./PrintView";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from "recharts";
import { exportCurriculumPDF } from "../../utils/pdfExport";

const BLOOM_COLORS = {
  Remember: "#6366f1",
  Understand: "#8b5cf6",
  Apply: "#06b6d4",
  Analyze: "#f59e0b",
  Evaluate: "#ef4444",
  Create: "#10b981",
};

export default function CurriculumDashboard({ curriculum, onReset, onShowHistory }) {
  const [activeDay, setActiveDay] = useState(1);
  const [activeTab, setActiveTab] = useState("lesson"); // lesson | quiz | activity
  const [showPrint, setShowPrint] = useState(false);
  const [quizScores, setQuizScores] = useState({}); // {day: {correct: n, total: n}}

  const handleQuizAnswer = (day, qIndex, isCorrect) => {
    setQuizScores((prev) => {
      const current = prev[day] || { correct: 0, total: 0 };
      return {
        ...prev,
        [day]: {
          correct: current.correct + (isCorrect ? 1 : 0),
          total: current.total + 1,
        },
      };
    });
  };

  const { meta, objectives, lessonPlans, quizzes, activities, resources, weeklyProject, progression } = curriculum;

  const currentLesson = lessonPlans?.find((d) => d.day === activeDay) || lessonPlans?.[0];
  const currentQuiz = quizzes?.find((d) => d.day === activeDay) || quizzes?.[0];
  const currentActivity = activities?.find((d) => d.day === activeDay) || activities?.[0];
  const currentObjective = objectives?.objectives?.find((o) => o.day === activeDay);

  const chartData = progression?.progression?.map((p) => ({
    day: `Day ${p.day}`,
    score: p.score,
    label: p.label,
  })) || [];

  return (
    <>
    {showPrint && <PrintView curriculum={curriculum} onClose={() => setShowPrint(false)} />}
    <div className="dashboard">
      {/* ── Header ── */}
      <div className="dash-header">
        <div className="dash-meta">
          <button className="back-btn" onClick={onReset}>← New Curriculum</button>
          <div className="meta-pills">
            <span className="meta-pill">{meta.ageGroup}</span>
            <span className="meta-pill">{meta.difficulty}</span>
            {meta.specialNeeds !== "None" && <span className="meta-pill accent-pill">♿ {meta.specialNeeds}</span>}
          </div>
        </div>
        <div className="dash-title-row">
          <div>
            <h1 className="dash-title">{meta.topic}</h1>
            <p className="dash-subtitle">5-Day Curriculum · Generated by Foundry IQ Agent</p>
            {meta.iqSource && (
              <div className="iq-source-row">
                <span className={"iq-badge " + (meta.iqSource === "foundry_iq" ? "iq-live" : "iq-static")}>
                  {meta.iqSource === "foundry_iq" ? "🟢 Foundry IQ Live" : "⚪ Foundry IQ (Static Fallback)"}
                </span>
                {meta.generationTimeMs && (
                  <span className="gen-time">Generated in {(meta.generationTimeMs/1000).toFixed(1)}s</span>
                )}
              </div>
            )}
          </div>
          <div className="dash-actions">
            <button className="history-nav-btn" onClick={onShowHistory}>📚 History</button>
            <button className="print-nav-btn" onClick={() => setShowPrint(true)}>🖨️ Print</button>
            <button className="pdf-btn" onClick={() => exportCurriculumPDF(curriculum)}>📄 Export PDF</button>
          </div>
        </div>
      </div>

      {/* ── Objectives Strip ── */}
      <div className="objectives-strip">
        {objectives?.objectives?.map((obj) => (
          <div
            key={obj.day}
            className={`obj-card ${activeDay === obj.day ? "obj-active" : ""}`}
            onClick={() => setActiveDay(obj.day)}
          >
            <div className="obj-day">Day {obj.day}</div>
            <div className="obj-text">{obj.objective}</div>
            <div
              className="bloom-badge"
              style={{ background: BLOOM_COLORS[obj.bloom_level] || "#6366f1" }}
            >
              {obj.bloom_level}
            </div>
          </div>
        ))}
      </div>

      {/* ── Main Content + Sidebar ── */}
      <div className="dash-body">
        <div className="dash-main">
          {/* Day selector tabs */}
          <div className="day-tabs">
            {[1, 2, 3, 4, 5].map((d) => (
              <button
                key={d}
                className={`day-tab ${activeDay === d ? "day-tab-active" : ""}`}
                onClick={() => setActiveDay(d)}
              >
                Day {d}
              </button>
            ))}
          </div>

          {/* Content tabs */}
          <div className="content-tabs">
            {["lesson", "quiz", "activity"].map((t) => (
              <button
                key={t}
                className={`content-tab ${activeTab === t ? "content-tab-active" : ""}`}
                onClick={() => setActiveTab(t)}
              >
                {t === "lesson" ? "📋 Lesson Plan" : t === "quiz" ? "✏️ Quiz" : "🎯 Activity"}
              </button>
            ))}
          </div>

          {/* ── LESSON PLAN TAB ── */}
          {activeTab === "lesson" && currentLesson && (
            <div className="lesson-card">
              <div className="lesson-header">
                <h2>{currentLesson.title}</h2>
                {currentObjective && (
                  <div className="objective-banner">
                    <strong>Objective:</strong> {currentObjective.objective}
                  </div>
                )}
              </div>

              {objectives?.teaching_approach && activeDay === 1 && (
                <div className="teaching-approach-banner">
                  <span className="ta-label">💡 Teaching Approach</span>
                  <span>{objectives.teaching_approach}</span>
                </div>
              )}

              <div className="lesson-timeline">
                {currentLesson.lesson_plan && Object.entries(currentLesson.lesson_plan).map(([key, val]) => (
                  <div key={key} className="timeline-item">
                    <div className="timeline-time">{val.duration}</div>
                    <div className="timeline-content">
                      <div className="timeline-phase">{key.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase())}</div>
                      <div className="timeline-desc">{val.description}</div>
                      {val.method && <div className="timeline-method">{val.method}</div>}
                    </div>
                  </div>
                ))}
              </div>

              {currentLesson.materials_needed && (
                <div className="materials-section">
                  <h4>Materials Needed</h4>
                  <div className="materials-list">
                    {currentLesson.materials_needed.map((m, i) => (
                      <span key={i} className="material-chip">{m}</span>
                    ))}
                  </div>
                </div>
              )}

              {currentLesson.differentiation && (
                <div className="differentiation-section">
                  <h4>Differentiation Strategies</h4>
                  <div className="diff-grid">
                    <div className="diff-card support">
                      <div className="diff-label">🤝 For Struggling Learners</div>
                      <div>{currentLesson.differentiation.for_struggling}</div>
                    </div>
                    <div className="diff-card advanced">
                      <div className="diff-label">🚀 For Advanced Learners</div>
                      <div>{currentLesson.differentiation.for_advanced}</div>
                    </div>
                    <div className="diff-card special">
                      <div className="diff-label">♿ Special Needs Adaptation</div>
                      <div>{currentLesson.differentiation.for_special_needs}</div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── QUIZ TAB ── */}
          {activeTab === "quiz" && currentQuiz && (
            <div className="quiz-card">
              <div className="quiz-header">
                <h2>Day {currentQuiz.day} Assessment</h2>
                <div className="difficulty-badge">Difficulty: {currentQuiz.difficulty_score}/10</div>
              </div>
              {quizScores[currentQuiz.day] && (
                <div className="quiz-score-bar">
                  <div className="quiz-score-label">
                    Score: {quizScores[currentQuiz.day].correct} / {quizScores[currentQuiz.day].total}
                  </div>
                  <div className="quiz-score-track">
                    <div
                      className="quiz-score-fill"
                      style={{
                        width: `${(quizScores[currentQuiz.day].correct / quizScores[currentQuiz.day].total) * 100}%`,
                        background: quizScores[currentQuiz.day].correct === quizScores[currentQuiz.day].total ? "var(--green)" : "var(--primary)"
                      }}
                    />
                  </div>
                  {quizScores[currentQuiz.day].total === currentQuiz.questions?.length && (
                    <div className="quiz-complete-msg">
                      {quizScores[currentQuiz.day].correct === currentQuiz.questions.length
                        ? "🎉 Perfect score!"
                        : quizScores[currentQuiz.day].correct >= currentQuiz.questions.length * 0.67
                        ? "✅ Good work!"
                        : "📖 Review the explanations and try again."}
                    </div>
                  )}
                </div>
              )}
              {currentQuiz.questions?.map((q, i) => (
                <QuizQuestion
                  key={`${currentQuiz.day}-${i}`}
                  question={q}
                  index={i}
                  onAnswer={(correct) => handleQuizAnswer(currentQuiz.day, i, correct)}
                />
              ))}
            </div>
          )}

          {/* ── ACTIVITY TAB ── */}
          {activeTab === "activity" && currentActivity && (
            <div className="activity-card">
              <div className="activity-header">
                <h2>{currentActivity.title}</h2>
                <span className="activity-type-badge">{currentActivity.type}</span>
              </div>
              <p className="activity-desc">{currentActivity.description}</p>

              <div className="instructions-section">
                <h4>Step-by-Step Instructions</h4>
                <ol className="instructions-list">
                  {currentActivity.instructions?.map((step, i) => (
                    <li key={i}>{step}</li>
                  ))}
                </ol>
              </div>

              <div className="activity-meta-row">
                <div className="activity-meta-item">
                  <span className="meta-icon">⏱️</span>
                  <span>{currentActivity.estimated_time}</span>
                </div>
                <div className="activity-meta-item">
                  <span className="meta-icon">🎯</span>
                  <span>{currentActivity.learning_outcome}</span>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* ── SIDEBAR ── */}
        <div className="dash-sidebar">
          {/* Difficulty Progression Chart */}
          <div className="sidebar-card">
            <h3>📈 Difficulty Progression</h3>
            <ResponsiveContainer width="100%" height={180}>
              <LineChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                <XAxis dataKey="day" tick={{ fontSize: 11, fill: "#94a3b8" }} />
                <YAxis domain={[0, 10]} tick={{ fontSize: 11, fill: "#94a3b8" }} />
                <Tooltip
                  contentStyle={{ background: "#0f172a", border: "1px solid #1e293b", borderRadius: "8px" }}
                  labelStyle={{ color: "#f1f5f9" }}
                />
                <Line type="monotone" dataKey="score" stroke="#6366f1" strokeWidth={2} dot={{ fill: "#6366f1", r: 5 }} />
              </LineChart>
            </ResponsiveContainer>
            {progression?.rationale && (
              <p className="chart-note">{progression.rationale}</p>
            )}
          </div>

          {/* Weekly Project */}
          {weeklyProject && (
            <div className="sidebar-card project-card">
              <h3>🏆 Weekly Project</h3>
              <div className="project-title">{weeklyProject.title}</div>
              <p>{weeklyProject.description}</p>
              <div className="deliverable-section">
                <strong>Deliverable:</strong> {weeklyProject.deliverable}
              </div>
              <div className="rubric-section">
                <strong>Rubric:</strong>
                <ul>
                  {weeklyProject.rubric?.map((r, i) => <li key={i}>{r}</li>)}
                </ul>
              </div>
            </div>
          )}

          {/* Resources */}
          {resources && resources.length > 0 && (
            <div className="sidebar-card">
              <h3>📚 Resources</h3>
              {resources.slice(0, 5).map((r, i) => (
                <div key={i} className="resource-item">
                  <div className="resource-type">{r.type}</div>
                  <div className="resource-title">{r.title}</div>
                  <div className="resource-desc">{r.description}</div>
                  {r.url && r.url !== "string" && (
                    <a href={r.url} target="_blank" rel="noreferrer" className="resource-link">
                      Open →
                    </a>
                  )}
                </div>
              ))}
            </div>
          )}

          {/* Prerequisites */}
          {objectives?.prerequisites && (
            <div className="sidebar-card">
              <h3>✅ Prerequisites</h3>
              <ul className="prereq-list">
                {objectives.prerequisites.map((p, i) => <li key={i}>{p}</li>)}
              </ul>
            </div>
          )}

          {/* Key Concepts */}
          {objectives?.key_concepts && objectives.key_concepts.length > 0 && (
            <div className="sidebar-card">
              <h3>🔑 Key Concepts</h3>
              <div className="key-concepts-list">
                {objectives.key_concepts.map((c, i) => (
                  <span key={i} className="concept-chip">{c}</span>
                ))}
              </div>
            </div>
          )}

          {/* Foundry IQ Citations */}
          {meta.iqCitations && meta.iqCitations.length > 0 && (
            <div className="sidebar-card citations-card">
              <h3>📖 Foundry IQ Sources</h3>
              <p className="citations-note">Pedagogical knowledge retrieved and grounded by Foundry IQ</p>
              <ul className="citations-list">
                {meta.iqCitations.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
    </>
  );
}

function QuizQuestion({ question, index, onAnswer }) {
  const [revealed, setRevealed] = useState(false);
  const [selected, setSelected] = useState(null);

  const handleSelect = (letter) => {
    if (revealed) return; // lock after reveal
    setSelected(letter);
    setRevealed(true);
    if (onAnswer) onAnswer(letter === question.correct_answer);
  };

  const isCorrectAnswer = selected === question.correct_answer;

  return (
    <div className={`quiz-question ${revealed ? (isCorrectAnswer ? "q-answered-correct" : "q-answered-wrong") : ""}`}>
      <div className="q-header">
        <span className="q-number">Q{index + 1}</span>
        <span className="q-bloom">{question.bloom_level}</span>
        {revealed && (
          <span className={`q-result-badge ${isCorrectAnswer ? "q-result-correct" : "q-result-wrong"}`}>
            {isCorrectAnswer ? "✓ Correct" : "✗ Incorrect"}
          </span>
        )}
      </div>
      <p className="q-text">{question.question}</p>
      <div className="q-options">
        {question.options?.map((opt, i) => {
          const letter = opt[0];
          const isCorrect = letter === question.correct_answer;
          const isSelected = selected === letter;
          return (
            <button
              key={i}
              className={`q-option
                ${isSelected && !revealed ? "q-selected" : ""}
                ${revealed && isCorrect ? "q-correct" : ""}
                ${revealed && isSelected && !isCorrect ? "q-wrong" : ""}
              `}
              onClick={() => handleSelect(letter)}
              disabled={revealed}
            >
              {opt}
              {revealed && isCorrect && <span className="q-check">✓</span>}
            </button>
          );
        })}
      </div>
      {revealed && (
        <div className="q-explanation">
          <strong>✓ Answer: {question.correct_answer}</strong> — {question.explanation}
        </div>
      )}
    </div>
  );
}
